#+title: 'AI' in Mathematics
#+hugo_custom_front_matter: :hidePagination true

A lot is happening in the world of mathematics. The future of the field seems more uncertain than ever. At a time like this, I think it is of great importance to stay informed and have healthy and thorough discussions among the mathematical community about what /we/ think all of this means for /us/ and where /we/ think things should go from here. This is especially true given the enormity of the companies involved, their clear disregard for the research ethics of our community, and the misinformation and obfuscation introduced by both their humans and their machines. *If the situation was hopeless, their propaganda would be unnecessary.*

In sorting my thoughts, I found it helpful to compile a list of essays, articles, talks, interviews, etc. that I thought were insightful. I've also collected some excerpts of said sources that I consider to be particularly interesting or important. Maybe this page can also be of use to someone else.

I took the liberty to add emphasis in bold face to some quotations. Emphasis in italics was already part of the original quoted text.

* General Commentary on Doing Mathematics
- [[https://arxiv.org/pdf/math/9404236][/On Proof and Progress in Mathematics/, William P. Thurston (1994)]]

#+BEGIN_QUOTE
    We are not trying to meet some abstract production quota of definitions, theorems and proofs. The measure of our success is whether what we do enables /people/ to understand and think more clearly and effectively about mathematics.
#+END_QUOTE

#+BEGIN_QUOTE
  In not too many years, I expect that we will have interactive computer programs that can help people compile significant chunks of formally complete and correct mathematics (based on a few perhaps shaky but at least explicit assumptions), and that they will become part of the standard mathematician’s working environment.
  However, we should recognize that the humanly understandable and humanly checkable proofs that we actually do are what is most important to us, and that they are quite different from formal proofs. 
#+END_QUOTE

#+BEGIN_QUOTE
    This phenomenon convinces me that the entire mathematical community would become much more productive if we open our eyes to the real values in what we are doing. Jaffe and Quinn propose a system of recognized roles divided into “speculation” and “proving”. Such a division only perpetuates the myth that our progress is measured in units of standard theorems deduced. [...] *What we are producing is human understanding.* We have many different ways to understand and many different processes that contribute to our understanding. We will be more satisfied, more productive and happier if we recognize and focus on this.
#+END_QUOTE

#+BEGIN_QUOTE
    What mathematicians most wanted and needed from me was to *learn my ways of thinking, and not in fact to learn my proof* of the geometrization conjecture for Haken manifolds.
#+END_QUOTE

- [[https://www.mimuw.edu.pl/~pawelst/rzut_oka/Zajecia_dla_MISH_2011-12/Lektury_files/LockhartsLament.pdf][/A Mathematician’s Lament/, Paul Lockhart (2002)]]

#+BEGIN_QUOTE
    Waking up in a cold sweat, the musician realizes, gratefully, that it was all just a crazy dream. “Of course!” he reassures himself, “No society would ever reduce such a beautiful and meaningful art form to something so mindless and trivial; no culture could be so cruel to its children as to deprive them of such a natural, satisfying means of human expression. How absurd!”
#+END_QUOTE

#+BEGIN_QUOTE
    The first thing to understand is that *mathematics is an art.* The difference between math and the other arts, such as music and painting, is that our culture does not recognize it as such. [...] Part of the problem is that nobody has the faintest idea what it is that mathematicians do. [...]
#+END_QUOTE

#+BEGIN_QUOTE
    By removing the creative process and leaving only the results of that process, you virtually guarantee that no one will have any real engagement with the subject. It is like /saying/ that Michelangelo created a beautiful sculpture, without letting me /see/ it. How am I supposed to be inspired by that? (And of course it’s actually much worse than this— at least it’s understood that there /is/ an art of sculpture that I am being prevented from appreciating).
    
    By concentrating on /what,/ and leaving out /why,/ mathematics is reduced to an empty shell. The art is not in the “truth” but in the explanation, the argument. It is the argument itself which gives the truth its context, and determines what is really being said and meant. Mathematics is /the art of explanation./
#+END_QUOTE


#+BEGIN_QUOTE
    /Simplicio:/ Alright, I’m thoroughly depressed. What now?
    
    /Salviati:/ Well, I think I have an idea about a pyramid inside a cube…
#+END_QUOTE



* General Commentary on Moving Forward in Math with AI
- [[https://www.youtube.com/watch?v=M0--ZH1lOzg][/Mathematics in the age of AI/, Terence Tao at the ICM 2026]]
#+BEGIN_QUOTE
#+begin_details
#+begin_summary
/Click to expand long quote on *canonicalization.*/
#+end_summary
    Even when a result has been accepted by the community and is published and is in a prestigious journal and people all accept it's correct, it's still not the final state. The final states are things like *textbooks,* the material that we teach in classes. What is the standard definition of this concept? What is the correct order in which we prove things? How do you organize individual results published in good papers into a coherent theory? [...] Alex, who introduced me, has a very nice name for this, it's *canonicalization*. So in addition to digesting a proof and publishing it, you want to make it canonical. And this is the slowest stage of all. You know, there's many many results in the last 10 years, 20 years, that are in prestigious journals but not in textbooks yet. They're not yet taught to students. We haven't yet figured out the really definitive canonical correct way to teach these things.

    And this is slow. You have to teach classes. You have to get feedback and you have to really think hard about what is the correct way to organize lots and lots of different results and put in one coherent narrative. And it needs consensus. If half the mathematicians in a field think you should do things this way and the other half a different way, we don't have canonicalization.
    
    *And this is the stage in which AI is basically completely useless.* I see basically almost no role for AI in this part of the process. *But it is the most valuable part.* If you want to apply any subfield of mathematics to some other area of mathematics or some problem it pretty much has to be digested in this form. If you want a field of math to become useful to engineers or physicists or biologists or whatever, they're not going to dig through the most recent papers in the annals of mathematics or whatever. So the most valuable applications of math only get unlocked once you have reached this final stage, *including AI itself.* A big reason why AI is so successful at mathematics is because for centuries we've been building these canonical definitions. We have these textbooks, you know, how does linear algebra work, how does group theory work, we have all these very very mature theories. And AI has absorbed all of these. And that's what it uses for success. *If we cut off this part of the process long term, it will hurt mathematics.*
#+end_details
#+END_QUOTE

- [[https://www.youtube.com/watch?v=H7_d_sgui6o][Panel Discussion /'AI in Mathematical Research'/ at the Heidelberg Laureate Forum,]] with Michael Harris, Peter Scholze, Jacob Tsimerman and Geordie Williamson

- [[https://www.youtube.com/watch?v=CBYhaKgah5U][Numberphile Podcast with Grant Sanderson (3Blue1Brown)]] 
#+BEGIN_QUOTE
/Brady Haran:/ Are you saying that mathematicians, at a fundamental professional level, need to be *explainers* as much as they are discoverers and explorers?

/Grant Sanderson:/ I do. [...] This is not like a new thing. Mathematicians do this with their time. But the impression I get is that that always feels second-class. It always feels like a second-tier version of what they're doing compared to proving new results. [...] We all acknowledge this is about human understanding. I think that the status of that kind of work [...] *deserves the same credit.*
#+END_QUOTE
- [[https://terrytao.wordpress.com/2026/09/18/if-math-is-more-than-proof-we-need-to-better-celebrate-the-rest-of-it/][/If math is more than proof, we need to better celebrate the rest of it,/]] guest post by Grant Sanderson on Terence Tao's blog
  + /Personal thought:/ I find [[https://terrytao.wordpress.com/2026/09/18/if-math-is-more-than-proof-we-need-to-better-celebrate-the-rest-of-it/comment-page-1/#comment-695756][this comment]] to be quite interesting. Why is it that this kind of argument seems plausible to us for mathematics (it has quite a few upvotes), but is rather clearly undesirable when it comes to art? (as [[https://terrytao.wordpress.com/2026/09/18/if-math-is-more-than-proof-we-need-to-better-celebrate-the-rest-of-it/comment-page-1/#comment-695955][a reply to the comment]] also suggests; see also [[https://www.youtube.com/watch?v=U8dcFhF0Dlk][this video essay]])
- [[https://youtu.be/Nbwv5wHQoj0?si=fBb1vZaBnu33_K6k&t=2755][/The last IMO problem AI could not solve/, 3Blue1Brown & PolyaMath]] (in particular the last chapter)
#+BEGIN_QUOTE
  This question doesn't contribute to a deep understanding of mathematics, nor is it particularly difficult (when compared with mathematical research). Rather the value of this question lies in the fact that it *warmed my heart when I solved it,* and it still warms my heart more than a year later. Like a good book or a touching song, *the value here is human.* Call me humanist, but I truly believe that the value of this question, as a mathematical discovery, exceeds that of the average PhD thesis.
  --- Aviv Tavor
#+END_QUOTE

- [[https://www.youtube.com/watch?v=G8HMa_tgM34][Tom Rocks Maths interviews Fields medalist Martin Hairer]]
- [[https://terrytao.wordpress.com/2026/09/07/finite-time-blowup-with-smooth-forcing-term-for-the-incompressible-porous-medium-boussinesq-and-incompressible-euler-equations/comment-page-1/#comment-694321][Terence Tao's thoughts on his stance towards AI and how it might have changed over time]]
* Declarations
- [[https://leidendeclaration.ai/][Leiden Declaration on Artificial Intelligence and Mathematics]] 
- [[https://mathandai.org/][Math and AI: /A Severe Misalignment of AI in Mathematics/]] (signed by 28 Fields medalists)
- [[https://www.ahmath.org][The Association for Human Mathematics (AHM)]]
* Policies & Regulations 
- [[https://blog.arxiv.org/2026/10/01/updated-rate-limit-policy/][arXiv limits submissions to two per month]]
* Results pre Navier-Stokes
The purpose of this section is not to compile a list of results proved using LLMs, but to provide some critical context and attempt to give some attribution to prior work, something that the LLMs often do not do.

- Jacobian Conjecture counterexample and it's relation to a paper by Vitushkin
  - [[https://x.com/__alpoge__/status/2079028340955197566][the infamous tweet]]
  - [[https://x.com/b_shrir/status/2079094004885668003?s=20][tweet]] and [[https://claude.ai/share/22abed98-d9af-43c5-9881-b19e009a07b0][Claude session]] by Sriram Balasubramanian investigating the origin of the counterexample
  - [[https://terrytao.wordpress.com/2026/07/21/a-digestion-of-the-jacobian-conjecture-counterexample/][blog post]] by Terence Tao and [[https://terrytao.wordpress.com/2026/07/21/a-digestion-of-the-jacobian-conjecture-counterexample/comment-page-1/#comment-693534][relevant comments]]
- Non-Sofic groups
  - [[https://www.youtube.com/watch?v=RhqHJ6vLBek][DorFuchs interviews Andreas Thom]] /(in German)/
  - [[https://mathstodon.xyz/@andreasthom/117240535270608201][later Mastodon posts by Andreas Thom]] (in response to Buckmaster's statement)
- new high-rank elliptic curves
  - Levent Alpöge and Ava Howell find a rank at least 30 elliptic curve using Claude
  - Samuel Li finds a rank at least 31 elliptic curve, and in the process reverse-engineers the above example, showing that Claude relied on the previously known method due to Noam Elkies and Zev Klagsbrun
  - [[https://www.youtube.com/watch?v=8C5LEpYQRo0][video on the topic by Alvaro Lozano-Robledo]]
* The whole Navier-Stokes Situation
- [[https://en.wikipedia.org/wiki/Navier%E2%80%93Stokes_priority_controversy][Wikipedia article]] 
- [[https://mastodon.social/@tristanbuckmaster/117233413705701198][Mastodon posts by Tristan Buckmaster]], including [[https://cims.nyu.edu/~tristanb/statement.pdf][statement.pdf]]
#+BEGIN_QUOTE
    Sebastien twice asserted that he wanted Levent removed from authorship, and said it would all be simple if only it were not the case that, and it was so annoying that, Levent works at Anthropic.
#+END_QUOTE
#+BEGIN_QUOTE
    I said that if OpenAI released its result in the way proposed I would go public with what happened. The reply was, “Why would you ruin your career?” I replied that I am an academic, and asked why he thought going public would ruin my career. The reply was, “If you don’t want me to be nice, then I don’t have to be nice.”
#+END_QUOTE
- [[https://openai.com/index/navier-stokes-solution/][Official OpenAI statement & papers]] (in its current form)
- [[https://mathstodon.xyz/@emilyriehl/117240246139472787][OpenAI quietly added citations after criticism]]
- Talk by Tristan Buckmaster: [[https://www.youtube.com/watch?v=tn45ZOp3lXM][/Blow-up for incompressible Euler equations/]]
- [[https://www.youtube.com/watch?v=Mzbtj5nkMXI][Numberphile interview with Tristan Buckmaster]]
#+BEGIN_QUOTE
And you have to put this into the context is that OpenAI have admitted (not for our project) that their agents have actually even gone so far as hacking another competitor's GitHub repository in order to solve a math problem. So I think it was just a few days ago that they announced that agents were working on some math problem, and then they realized that there was another team working on it and then they managed to get like the token which allowed them access to the GitHub repository of their competitors in order to solve the problem. I mean there's so many ways in which that they could get access to our work.

And the key thing here is that, to get to the Navier-Stokes problem, they used 10,000 agents. They didn't use 10,000 agents to get to the Euler problem. They used 100 agents. So they worked from absolutely nothing with only 100 agents. And that is key, because number of agents means like how wide you can search. And they used 100 agents and then they ended up with an identical architecture to what we had.
#+END_QUOTE

#+BEGIN_QUOTE
[...] it isn't about the internal models, it's about using a lot of them. [...] And I think I saw an OpenAI employee making this claim that it's all about the internal models and it's like 90% the internal model and 10% [the number of agents]; It's the opposite way around. It's maybe 20, 30, I don't know, percent internal models and then the rest of it is using all these different agents within a particular harness or particular framework in order to solve a problem.
#+END_QUOTE

- [[https://www.youtube.com/watch?v=0ImH35gLHwQ][DorFuchs interviews Andreas Thom on this topic]] /(in German)/


* Outside of Mathematics
- [[https://www.youtube.com/watch?v=U8dcFhF0Dlk][/Suno, AI Music, and the Bad Future,/ Adam Neely]] (*<- highly recommended*)
- [[https://www.youtube.com/watch?v=DY_LgqIh40k][Philosoph Rainer Mühlhoff über Künstliche Intelligenz & Faschismus, Jung & Naiv]] /(in German)/

